### ISSUE TITLE
[FEATURE] - Add editor for certain configurations

### ISSUE THREAD

**Issue by TG-Web-Team** [expung3d/A3-RolesSystem#1]
I've communicated the following to Expunged but just wanted it to be officially here 😉

#1 Ability for ZM or Moderator to enable partial or all roles (Basic, Specialists & support) when there's at least 2 members in a squad. For example, would be useful for 2 man sniper Squad (spotter and sniper) or squads of 4 that requires HAT or other types of roles.

We love the fact there's a max # of a specific role per squad. For example, 2 Medics or 2 HAT. Very similar to I&A. Keeps a good balance 👍

#2 Ability for ZM or Moderator to edit attachments or accessories of a specific Role. For example, Rifleman should have the ability to have additional scopes or change binoculars to laser designator.

But we love the fact that a Rifleman is not a Grenadier which disables the Grenade luncher or the fact that he can't grab AT. 👍

#3 Ability for ZM or Moderator to initiate vote for Ground Command or assign Ground Command.

Thanks for your hard work guys!

**Comment by expung3d** [comment]
#1 will eventually be done in some way. We've had this suggestion for a while. However, it will be a complicated thing to implement.

#2 is planned. There will be a config editor that will let you create configs for specific roles on maps in an easy to use GUI.

#3 is already a thing since the official release.

**Comment by expung3d** [comment]
The Config Editor has been added, hot swapping is being added with V1.5.3

**Comment by expung3d** [comment]
Version 1.5.3 is live.
