### ISSUE TITLE
[BUG] - toggles and map zeus bug

### ISSUE THREAD

**Issue by JustanSun** [expung3d/A3-RolesSystem#16]
roles system toggle options dont work at all. it pops up a hint that says no func name.
 

The roles system messes with the zeus sometimes when he dies and respawns. he will get stuck in map with no way to exit, with the roles sytem asking him to agree to the message thingyy.

**Comment by JustanSun** [comment]
toggles refer to von, and other ones. commander vote was not working either

**Comment by expung3d** [comment]
This is caused by an old version of EZM conflicting with the modules.
