### ISSUE TITLE
[FEATURE] - add mk200 to heavy gunner

### ISSUE THREAD

**Issue by JustanSun** [expung3d/A3-RolesSystem#8]
not a complicated request, please add the mk200 lmg to the heavy gunner or autorifleman slot, it would make sense for this to be a thing. possibly add the fia 50 cal backpacks too? it would make sense for a heavy weapons team to carry those.

**Comment by expung3d** [comment]
I don't believe this will be added to Heavy Gunner, given its only 6.5mm. If anything, it will be added to NATO autorifleman, however, they already have 3 options and the Mk200 is given to the AAF autorifleman.

**Comment by expung3d** [comment]
This won't be changed in the default configs.
