### ISSUE TITLE
[FEATURE] - Replace sniper with sharpshooter

### ISSUE THREAD

**Issue by Zaco-Kick** [expung3d/A3-RolesSystem#9]
snipers typically do not work well in teams and the role is too restricting with just ghillies.
Change the sniper to have more weapons sights uniforms etc to make it a better form of the marksman and renamed the role to sharpshooter

**Comment by TG-Web-Team** [comment]
I would force snipers to be in a Squad of at least 2. Sniper and spotter.

**Comment by expung3d** [comment]
This is a good improvement on the current design for Snipers. Will implement.

**Comment by expung3d** [comment]
Changed with V1.4.0
